# Generated by Django 5.1.2 on 2024-10-12 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_queue'),
        ('manager', '0007_delete_seat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together={('user', 'event')},
        ),
        migrations.AddField(
            model_name='queue',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='queue',
            name='created_at',
        ),
    ]
