# Generated by Django 5.1.2 on 2024-10-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_temp_disabled',
            new_name='is_temp_locked',
        ),
    ]
