# Generated by Django 5.1.2 on 2024-10-12 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_seat_booked_by_alter_seat_seat_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
