# Generated by Django 5.1.2 on 2024-10-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
