# Generated by Django 5.1.2 on 2024-10-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_event_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
